# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# SALES PREDICTION WITH GRAPH

import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# Data
TV = [230, 44, 17, 151, 180]
Radio = [37, 39, 45, 41, 10]
Newspaper = [69, 45, 69, 58, 58]

Sales = [22, 10, 9, 18, 12]

# Input data
X = []

for i in range(len(TV)):
    X.append([TV[i], Radio[i], Newspaper[i]])

y = Sales

# Model
model = LinearRegression()
model.fit(X, y)

# Prediction
prediction = model.predict([[200, 40, 50]])

print("Predicted Sales:", prediction[0])

# Accuracy
accuracy = model.score(X, y)

print("Accuracy:", accuracy)

# GRAPH
plt.plot(Sales, marker='o')

plt.title("Sales Prediction Graph")
plt.xlabel("Data Points")
plt.ylabel("Sales")

plt.show()